swagger: "2.0"
info:
  description: "Api para fazer checkout"
  version: "1.0.0"
  title: "Checkout"
  contact:
    email: "contato@adaga.cc"

host: "localhost"

tags:
- name: "Checkout"
  description: "API de checkout"

schemes:
- "https"
- "http"
paths:
  /checkout:
    post:
      tags:
      - "Checkout"
      summary: "Criar uma fatura de checkout"
      description: "Usado para criar uma fatura que pode ser paga por API ou por nossa interface de fatura (paymentLink)"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Request para criação de cobrança"
        required: true
        schema:
          $ref: "#/definitions/Checkout"
      responses:
        "200": 
          description: Resposta
          schema:
            $ref: "#/response/CheckoutResponse"
        "400":
          description: "Dados de INPUT inválido"
        "500":
          description: "Server internal error"
  /checkout/read/{checkoutId}:
    get:
      tags:
      - "Checkout"
      summary: "Consultar um checkout"
      description: "Usado para consultar um checkout"
      parameters:
      - name: "checkoutId"
        in: "path"
        description: "Consultar dados do checkout"
        required: true
        type: "string"
      responses:
        "200": 
          description: Resposta
          schema:
            $ref: "#/response/ReadCheckoutResponse"
        "404":
          description: "Checkout não encontrado"
        "500":
          description: "Server internal error"
  /checkout/card-payment:
    post:
      tags:
      - "Checkout"
      summary: "Pagar um checkout com cartão"
      description: "API para efetuar o pagamento do check-out com cartão"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Request para criação de cobrança"
        required: true
        schema:
          $ref: "#/definitions/CardPayment"
      responses:
        "200": 
          description: Resposta
          schema:
            $ref: "#/response/CardPaymentResponse"
            
        "400":
          description: "Dados de INPUT inválido"
        "412":
          description: "Checkout já pago | Checkout já cancelado | Checkout ainda está sendo processado | Checkout está em contestação | Quantidade de parcelas excede o limite pré-definido"
        "500":
          description: "Server internal error"

  /checkout-change-status:
    post:
      tags:
      - "Notificação Webhook"
      summary: "Notificar a alteração do status de um checkout"
      description: "Notificamos a alteração do status de um checkout"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "Secret"
        in: "header"
        description: "notificationSecret que foi fornecido na criação do checkout"
        required: false
        type: "string"
      - in: "body"
        name: "body"
        description: "Corpo da request que enviamos"
        required: true
        schema:
          $ref: "#/definitions/Webhook"
          
      responses:
        "200": 
          description: Resposta
response:
  CardPaymentResponse:
    type: "object"
    required:
      - id
      - checkoutId
      - status
    properties:
      id:
        type: "string"
        description: "ID do pagamento"
      checkoutId:
        type: "string"
        description: "ID do checkout"
      status:
        type: string
        description: "Status do pagamento"
        enum:
          - pending_payment
          - processing
          - paid
          - refunded
          - rejected
          - canceled
          - in_dispute  
      
  ReadCheckoutResponse:
    type: "object"
    required:
      - id
      - amount
      - maxInstallments
      - qrCode
      - qrCodeJPEGBase64
      - status
    properties:
      id:
        type: "string"
        description: "ID do checkout"
      amount:
        type: "integer"
        description: "Valor em centavos, exemplo R$10,00 = 1000"
        format: "int64"
      maxInstallments:
        type: "integer"
        description: "Define um limite máximo de parcelas que nossa API permitirá pagamento, o parcelamento só funcionará em caso de pagamento com cartão, pois o pagamento via PIX sempre será a vista"
        minimum: 1
      qrCode:
        type: "string"
        description: "Conteúdo do QRCode"
      qrCodeJPEGBase64:
        type: "string"
        description: "Imagem (JPEG) do QRCode em Base64"
      status:
        type: string
        description: "Status do pagamento"
        enum:
          - pending_payment
          - processing
          - paid
          - refunded
          - rejected
          - canceled
          - in_dispute
      
  CheckoutResponse:
    type: "object"
    required:
      - id
      - paymentLink
      - qrCode
      - qrCodeJPEGBase64
    properties:
      id:
        type: "string"
        description: "ID do checkout"
      paymentLink:
        type: "string"
        description: "Link da fatura"
      qrCode:
        type: "string"
        description: "Conteúdo do QRCode"
      qrCodeJPEGBase64:
        type: "string"
        description: "Imagem (JPEG) do QRCode em Base64"
        

definitions:
  CardPayment:
    type: "object"
    required:
      - cardHolder
      - installments
      - cardToken
      - payerEmail
      - payerDocument
    properties:
      checkoutId:
        type: string
        description: ID o checkout (Se enviar null, será criado um novo checkout)
      amount:
        type: "integer"
        description: "Valor em centavos, exemplo R$10,00 = 1000 (Obrigatório se o checkoutId for null)"
        format: "int64"
      notificationUrl:
        type: "string"
        description: "É a URL onde notificaremos alteração do status da fatura (Obrigatório se o checkoutId for null)"
      notificationSecret:
        type: "string"
        description: "Enviaremos esse valor no HEADER da notificação para que seja confimardo a nossa autenticidade na notificação (Obrigatório se o checkoutId for null)"
      cardHolder:
        type: string
        description: Nome que está no cartão
      installments:
        type: integer
        description: Quantidade de parcelas (Não pode ser maior que o maxInstallments passado na criação)
        minimum: 1
      cardToken:
        type: string
        description: Token do cartão gerado com a SDK
      payerEmail:
        type: string
        description: E-mail do pagador
      payerDocument:
        type: string
        description: CPF/CNPJ do pagador
   
  Webhook:
    type: "object"
    required:
    - "checkoutId"
    - "status"
    properties:
      checkoutId:
        type: "string"
        description: "Id do checkout"
      refundAmount:
        type: "integer"
        description: "Em caso de estorno é retornado o valor da devolução"
        format: "int64"
      status:
        type: "string"
        description: "Novo status"
        enum:
          - pending_payment
          - processing
          - paid
          - refunded
          - rejected
          - canceled
          - in_dispute  
        
  Checkout:
    type: "object"
    required:
    - "amount"
    - "maxInstallments"
    - "notificationUrl"
    - "notificationSecret"
    - "payer"
    properties:
      amount:
        type: "integer"
        description: "Valor em centavos, exemplo R$10,00 = 1000"
        format: "int64"
      description:
        type: "string"
        description: "Descrição da cobrança"
      maxInstallments:
        type: "integer"
        description: "Define um limite máximo de parcelas que nossa API permitirá pagamento, o parcelamento só funcionará em caso de pagamento com cartão, pois o pagamento via PIX sempre será a vista"
        minimum: 1
      notificationUrl:
        type: "string"
        description: "É a URL onde notificaremos alteração do status da fatura"
      notificationSecret:
        type: "string"
        description: "Enviaremos esse valor no HEADER da notificação para que seja confimardo a nossa autenticidade na notificação"
      payer:
        $ref: "#/definitions/Payer"
        
  Payer:
    type: "object"
    required:
    - "name"
    - "email"
    - "document"
    - "address"
    properties:
      name:
        type: string
        description: nome de quem está realizando o pagamento
      email:
        type: string
        description: email do pagador
      document:
        type: string
        description: CPF/CNPJ de quem está realizando o pagamento
      address:
        $ref: "#/definitions/Address"
  Address:
    type: object
    required:
    - streetName
    - streetNumber
    - zipcode
    - neighborhood
    - city
    - uf
    properties:
      streetName: 
        type: "string"
        description: "nome da rua"
      streetNumber: 
        type: "string"
        description: "Numéro"
      zipcode: 
        type: "string"
        description: "CEP"
      neighborhood: 
        type: "string"
        description: "Bairro"
      city: 
        type: "string"
        description: "Nome da cidade"
      uf: 
        type: "string"
        example: SP
        description: "Sigla do estado"
        minLength: 2
        maxLength: 2
